// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt2bWeI4G3YM2vuR6pC8EH-Jdj5zi9kzA',
    appId: '1:60794186021:web:8abe5844cde250956752cc',
    messagingSenderId: '60794186021',
    projectId: 'foundme-28322',
    authDomain: 'foundme-28322.firebaseapp.com',
    storageBucket: 'foundme-28322.firebasestorage.app',
    measurementId: 'G-JN2P0CZNVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVdQonaiSwSo_41Pl1Y-8-kbfCrfvBBWA',
    appId: '1:60794186021:android:db868e10a9d420936752cc',
    messagingSenderId: '60794186021',
    projectId: 'foundme-28322',
    storageBucket: 'foundme-28322.firebasestorage.app',
  );

}